// SPDX-License-Identifier: Apache-2.0
//! The boards' memory maps, as LaTeX (issue 444).
//!
//! A board document lists the map its design decodes, and this writes
//! it from the design rather than from a copy: the router's ranges
//! and names are `BoardMap`'s, the peripheral page's are `SlotMap`'s,
//! and a peripheral's registers are the map its `regmap!` declares.
//! Each table is a definition, `\mm@<what>@<key>`, which the documents
//! read through `\mmget` in `docs/memmap.tex`; asking for one this
//! does not write stops the document, so a table cannot quietly go.
use txhdl::map::AddrMap;
use txhdl::regmap::RegMap;
use vreteno32::board::{BoardMap, SlotMap};

/// One LaTeX definition, `\mm@<what>@<key>`, holding `body`.
fn define(what: &str, key: &str, body: &str) {
    println!(
        "\\expandafter\\def\\csname mm@{what}@{key}\\endcsname{{%\n{body}}}"
    );
}

/// A table from a column spec, a header and rows.
fn table(cols: &str, head: &str, rows: &[String]) -> String {
    format!(
        "\\begin{{center}}\\footnotesize\n\\begin{{tabular}}{{@{{}}{cols}@{{}}}}\n\
         \\toprule\n{head} \\\\\n\\midrule\n{}\n\\bottomrule\n\
         \\end{{tabular}}\n\\end{{center}}\n",
        rows.join("\n")
    )
}

/// An address as the documents write one: `0x3000`, or in groups of
/// four digits past sixteen bits, `0x4000\_0000`.
fn addr(a: usize) -> String {
    let h = format!("{a:x}");
    if h.len() <= 4 {
        return format!("\\code{{0x{h}}}");
    }
    let h = format!("{a:08x}");
    format!("\\code{{0x{}\\_{}}}", &h[..4], &h[4..])
}

/// A size in the largest unit it is a whole number of.
fn size(n: usize) -> String {
    for (u, s) in [(1 << 30, "GiB"), (1 << 20, "MiB"), (1 << 10, "KiB")] {
        if n >= u && n.is_multiple_of(u) {
            return format!("{}~{s}", n / u);
        }
    }
    format!("{n}~bytes")
}

/// The ranges of a map, lowest first: the base, the last address, the
/// size and the name, with `names` in place of the map's own where
/// it gives one.
fn ranges<const N: usize, M: AddrMap<N>>(
    names: &[(usize, &str)],
) -> Vec<String> {
    let mut rs: Vec<(usize, usize, &str)> = (0..N)
        .map(|i| {
            let (base, mask) = M::RANGES[i];
            let n = (!mask & 0xffff_ffff) + 1;
            let name = names
                .iter()
                .find(|(k, _)| *k == i)
                .map_or(M::NAMES[i], |(_, s)| *s);
            (base, n, name)
        })
        .collect();
    rs.sort();
    rs.iter()
        .map(|(b, n, name)| {
            format!(
                "{} & {} & {} & {name} \\\\",
                addr(*b),
                addr(b + n - 1),
                size(*n)
            )
        })
        .collect()
}

/// The map of a board, keyed `key`, with `names` naming ranges of the
/// peripheral page differently from `SlotMap`, as a board that puts
/// something on the third slot does.
fn board(key: &str, slots: &[(usize, &str)]) {
    let cols = "lll>{\\raggedright\\arraybackslash}p{0.4\\linewidth}";
    let head = "Base & Last & Size & What is there";
    define(
        "board",
        key,
        &table(cols, head, &ranges::<7, BoardMap>(&[])),
    );
    define(
        "page",
        key,
        &table(cols, head, &ranges::<6, SlotMap>(slots)),
    );
}

/// A peripheral's registers, from the base the board gives it: the
/// rows its map writes for a datasheet, offsets from that base, and
/// its fields under each word.
fn regs(key: &str, base: usize, map: &RegMap) {
    let at = format!("\\noindent From {}.\\par\n", addr(base));
    define(
        "regs",
        key,
        &(at + &table(
            "llp{0.16\\textwidth}p{0.36\\textwidth}",
            "Offset & Register & Access & What it is",
            &map.tex_rows(),
        )),
    );
}

/// The peripherals on the page that declare their registers with
/// `regmap!`, by the slot they sit in: one to a line, and one more as
/// each peripheral's declaration lands.
/// The key is the one a document asks for, since every peripheral's
/// map is called `regs`.
fn page_maps() -> Vec<(usize, &'static str, &'static RegMap)> {
    vec![]
}

fn main() {
    println!("% Generated by //tools/memmap. Do not edit.");
    board("vreteno", &[]);
    board(
        "flagship",
        &[(2, "the video peripheral, on the pixel clock")],
    );
    for (slot, key, map) in page_maps() {
        let base = <SlotMap as AddrMap<6>>::RANGES[slot].0;
        regs(key, base, map);
    }
}
