// SPDX-License-Identifier: Apache-2.0
//! A Verilog module as a unit: from the module's port list, the C shim
//! over its Verilated model, and the Rust that makes a `Unit` of it,
//! for `verilog_unit()` in `lib/foreign.bzl`.
//!
//! The ports are read from the module header, ANSI style: `input`
//! or `output`, an optional `wire`, `reg` or `logic`, an optional
//! `signed`, an optional `[hi:lo]`, and the name. One port is the
//! clock, which the shim pulses; a port a bit wide is a `Bit`, a wider
//! one a `U<W>`; three ports `x_data`, `x_valid` and `x_ready` are a
//! channel `x`, into the module when the data comes in and out of it
//! when the data goes out.
//!
//! Usage: vshim MODULE.v TOP CLOCK NAME SHIM.cc UNIT.rs

struct Port {
    name: String,
    input: bool,
    width: usize,
}

enum Item {
    Wire(Port),
    /// A channel: its stem, the data width, and whether it comes into
    /// the module.
    Chan(String, usize, bool),
}

fn main() {
    let a: Vec<String> = std::env::args().collect();
    let (src, top, clock, name) = (&a[1], &a[2], &a[3], &a[4]);
    let (shim_out, rs_out) = (&a[5], &a[6]);
    let text = std::fs::read_to_string(src).expect("read the module");
    let ports = parse_ports(&text, top);
    let ports: Vec<Port> =
        ports.into_iter().filter(|p| p.name != *clock).collect();
    let items = group(&ports);
    std::fs::write(shim_out, shim(&ports, top, clock, name)).expect("shim");
    std::fs::write(rs_out, unit(&ports, &items, top, name)).expect("unit");
}

/// The header's ports, in order.
fn parse_ports(text: &str, top: &str) -> Vec<Port> {
    let at = text
        .find(&format!("module {top}"))
        .unwrap_or_else(|| panic!("no `module {top}` in the file"));
    let rest = &text[at..];
    let open = rest.find('(').expect("the port list");
    let close = rest.find(");").expect("the port list's end");
    let list = &rest[open + 1..close];
    let mut out = Vec::new();
    for entry in list.split(',') {
        let toks: Vec<&str> = entry.split_whitespace().collect();
        let Some(dir) =
            toks.iter().position(|t| *t == "input" || *t == "output")
        else {
            continue;
        };
        let input = toks[dir] == "input";
        let name = toks.last().expect("a port name").to_string();
        let width = toks
            .iter()
            .find(|t| t.starts_with('['))
            .map(|t| {
                let t = t.trim_matches(|c| c == '[' || c == ']');
                let (hi, lo) = t.split_once(':').expect("[hi:lo]");
                let (hi, lo): (usize, usize) =
                    (hi.parse().expect("hi"), lo.parse().expect("lo"));
                hi - lo + 1
            })
            .unwrap_or(1);
        out.push(Port { name, input, width });
    }
    out
}

/// The ports as the unit sees them: channels where three ports make
/// one, wires otherwise.
fn group(ports: &[Port]) -> Vec<Item> {
    let find = |n: &str| ports.iter().find(|p| p.name == n);
    let mut items = Vec::new();
    let mut taken: Vec<String> = Vec::new();
    for p in ports {
        if taken.contains(&p.name) {
            continue;
        }
        if let Some(stem) = p.name.strip_suffix("_data") {
            let (v, r) = (format!("{stem}_valid"), format!("{stem}_ready"));
            if let (Some(valid), Some(ready)) = (find(&v), find(&r)) {
                if valid.input == p.input && ready.input != p.input {
                    taken.extend([p.name.clone(), v, r]);
                    items.push(Item::Chan(stem.to_string(), p.width, p.input));
                    continue;
                }
            }
        }
        items.push(Item::Wire(Port {
            name: p.name.clone(),
            input: p.input,
            width: p.width,
        }));
    }
    items
}

/// The Verilator type of a port, by width.
fn ctype(width: usize) -> &'static str {
    match width {
        0..=8 => "CData",
        9..=16 => "SData",
        17..=32 => "IData",
        33..=64 => "QData",
        _ => "wide",
    }
}

fn shim(ports: &[Port], top: &str, clock: &str, name: &str) -> String {
    let mut o = String::new();
    o.push_str(&format!(
        "// Generated by //tools/vshim from module {top}: the C shim.\n\
         #include \"V{top}.h\"\n#include <cstdint>\n\n\
         extern \"C\" {{\n\
         void *{name}_new() {{ return new V{top}; }}\n\
         void {name}_free(void *m) {{ auto t = (V{top} *)m; t->final(); \
         delete t; }}\n\
         void {name}_eval(void *m) {{ ((V{top} *)m)->eval(); }}\n\
         void {name}_edge(void *m) {{ auto t = (V{top} *)m; t->{clock} = 1; \
         t->eval(); t->{clock} = 0; t->eval(); }}\n"
    ));
    o.push_str(&format!(
        "void {name}_set(void *m, uint32_t i, const uint32_t *w, uint32_t n) \
         {{\n  auto t = (V{top} *)m;\n  (void)n;\n  switch (i) {{\n"
    ));
    for (i, p) in ports.iter().enumerate() {
        if !p.input {
            continue;
        }
        let w = p.width;
        if ctype(w) == "wide" {
            let words = w.div_ceil(32);
            o.push_str(&format!(
                "  case {i}: for (uint32_t k = 0; k < {words} && k < n; k++) \
                 t->{}[k] = w[k]; break;\n",
                p.name
            ));
        } else {
            let mask = if w >= 64 {
                "".to_string()
            } else {
                format!(" & ((1ull << {w}) - 1)")
            };
            o.push_str(&format!(
                "  case {i}: t->{} = ({})(((uint64_t)w[0] | ((uint64_t)w[1] \
                 << 32)){mask}); break;\n",
                p.name,
                ctype(w)
            ));
        }
    }
    o.push_str("  default: break;\n  }\n}\n");
    o.push_str(&format!(
        "void {name}_get(void *m, uint32_t i, uint32_t *w, uint32_t n) {{\n  \
         auto t = (V{top} *)m;\n  for (uint32_t k = 0; k < n; k++) w[k] = 0;\n \
           \
         switch (i) {{\n"
    ));
    for (i, p) in ports.iter().enumerate() {
        if p.input {
            continue;
        }
        let w = p.width;
        if ctype(w) == "wide" {
            let words = w.div_ceil(32);
            o.push_str(&format!(
                "  case {i}: for (uint32_t k = 0; k < {words} && k < n; k++) \
                 w[k] = t->{}[k]; break;\n",
                p.name
            ));
        } else {
            o.push_str(&format!(
                "  case {i}: {{ uint64_t v = (uint64_t)t->{}; w[0] = \
                 (uint32_t)v; if (n > 1) w[1] = (uint32_t)(v >> 32); \
                 break; }}\n",
                p.name
            ));
        }
    }
    o.push_str("  default: break;\n  }\n}\n}\n");
    o
}

fn camel(s: &str) -> String {
    let mut o = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '_' {
            up = true;
        } else if up {
            o.extend(c.to_uppercase());
            up = false;
        } else {
            o.push(c);
        }
    }
    o
}

fn ty(width: usize) -> String {
    if width == 1 {
        "Bit".into()
    } else {
        format!("U<{width}>")
    }
}

fn tuple(xs: &[String]) -> String {
    match xs.len() {
        0 => "()".into(),
        1 => xs[0].clone(),
        _ => format!("({})", xs.join(", ")),
    }
}

fn unit(ports: &[Port], items: &[Item], top: &str, name: &str) -> String {
    let idx = |n: &str| ports.iter().position(|p| p.name == n).unwrap();
    let strukt = camel(top);
    let (mut in_ty, mut in_nm, mut out_ty, mut out_nm) =
        (Vec::new(), Vec::new(), Vec::new(), Vec::new());
    for it in items {
        match it {
            Item::Wire(p) if p.input => {
                in_ty.push(format!("In<{}>", ty(p.width)));
                in_nm.push(p.name.clone());
            }
            Item::Wire(p) => {
                out_ty.push(format!("Out<{}>", ty(p.width)));
                out_nm.push(p.name.clone());
            }
            Item::Chan(stem, w, true) => {
                in_ty.push(format!("Rx<{}>", ty(*w)));
                in_nm.push(stem.clone());
            }
            Item::Chan(stem, w, false) => {
                out_ty.push(format!("Tx<{}>", ty(*w)));
                out_nm.push(stem.clone());
            }
        }
    }
    let param = |nm: &[String], t: &[String]| -> String {
        if nm.is_empty() {
            "_none: ()".into()
        } else {
            format!("{}: {}", tuple(nm), tuple(t))
        }
    };
    // The step: inputs in, a settle, the transfers the module agrees
    // to, the edge, and the outputs out.
    let mut before = String::new();
    let mut after = String::new();
    let mut outs = String::new();
    let raw_in = |n: &str, w: usize| -> String {
        if w == 1 {
            format!("{n}.get().to_bool() as u128")
        } else {
            format!("{n}.get().raw()")
        }
    };
    let from_raw = |e: &str, w: usize| -> String {
        if w == 1 {
            format!("Bit::from_bool({e} != 0)")
        } else {
            format!("U::<{w}>::new({e})")
        }
    };
    for it in items {
        match it {
            Item::Wire(p) if p.input => before.push_str(&format!(
                "            m.set({}, {});\n",
                idx(&p.name),
                raw_in(&p.name, p.width)
            )),
            Item::Wire(p) => outs.push_str(&format!(
                "            {}.set({});\n",
                p.name,
                from_raw(&format!("m.get({})", idx(&p.name)), p.width)
            )),
            Item::Chan(s, w, true) => {
                let head = if *w == 1 {
                    format!("{s}.head().to_bool() as u128")
                } else {
                    format!("{s}.head().raw()")
                };
                before.push_str(&format!(
                    "            let {s}_offered = {s}.peek().is_some();\n \
                                \
                     m.set({}, {s}_offered as u128);\n            \
                     m.set({}, {head});\n",
                    idx(&format!("{s}_valid")),
                    idx(&format!("{s}_data"))
                ));
                after.push_str(&format!(
                    "            if {s}_offered && m.get({}) != 0 {{\n \
                                    \
                     {s}.recv();\n            }}\n",
                    idx(&format!("{s}_ready"))
                ));
            }
            Item::Chan(s, w, false) => {
                before.push_str(&format!(
                    "            let {s}_room = {s}.ready().to_bool();\n \
                                \
                     m.set({}, {s}_room as u128);\n",
                    idx(&format!("{s}_ready"))
                ));
                after.push_str(&format!(
                    "            if {s}_room && m.get({}) != 0 {{\n \
                                    \
                     {s}.send({});\n            }}\n",
                    idx(&format!("{s}_valid")),
                    from_raw(
                        &format!("m.get({})", idx(&format!("{s}_data"))),
                        *w
                    )
                ));
            }
        }
    }
    format!(
        "// Generated by //tools/vshim from module {top}: the unit.\n\
         //! `{top}`, a Verilog module under Verilator, as a unit.\n\
         #![allow(unused_imports, unused_variables, clippy::all)]\n\
         use txhdl::comp::{{Clock, DefaultClock, In, Out, Rx, Tx, Unit}};\n\
         use txhdl::foreign::{{Model, Shim}};\n\
         use txhdl::types::{{Bit, U}};\n\n\
         type H = *mut core::ffi::c_void;\n\n\
         extern \"C\" {{\n    \
         fn {name}_new() -> H;\n    \
         fn {name}_free(m: H);\n    \
         fn {name}_eval(m: H);\n    \
         fn {name}_edge(m: H);\n    \
         fn {name}_set(m: H, i: u32, w: *const u32, n: u32);\n \
             \
         fn {name}_get(m: H, i: u32, w: *mut u32, n: u32);\n \
         \
         }}\n\n\
         /// The module, its clock pulsed once per rising edge of the\n\
         /// default clock.\n\
         pub struct {strukt} {{\n    pub model: Model,\n}}\n\n\
         impl Default for {strukt} {{\n    fn default() -> Self {{\n        \
         Self {{\n            model: Model::new(Shim {{\n                \
         new: {name}_new,\n                free: {name}_free,\n                \
         eval: {name}_eval,\n                edge: {name}_edge,\n \
                         \
         set: {name}_set,\n                get: {name}_get,\n            \
         }}),\n        }}\n    }}\n}}\n\n\
         impl Unit<{}, {}> for {strukt} {{\n    \
         async fn run(&mut self, {}, {}) {{\n        \
         loop {{\n            DefaultClock::rising().await;\n            \
         let m = &self.model;\n{before}            m.eval();\n \
         {after}            \
         m.edge();\n{outs}        }}\n    }}\n}}\n",
        tuple(&in_ty),
        tuple(&out_ty),
        param(&in_nm, &in_ty),
        param(&out_nm, &out_ty),
    )
}
