load("@bazel_ebook//build:rules.bzl", "ebook_pdf", "markdown_lib", "pandoc_standalone_html")

package(default_visibility = ["//visibility:public"])

# ebook_pdf wants EPUB metadata even when only a PDF is asked for, and the
# specification has none to give.
genrule(
    name = "empty_xml_gen",
    outs = ["empty_gen.xml"],
    cmd = "touch $@",
)

markdown_lib(
    name = "language_md",
    srcs = ["language.md"],
)

ebook_pdf(
    name = "language-pdf",
    metadata_xml = ":empty_xml_gen",
    tags = ["pdf"],
    title_yaml = "title.yaml",
    deps = [
        ":language_md",
        "//:empty_md",
    ],
)

pandoc_standalone_html(
    name = "language-html",
    tags = ["html"],
    deps = [
        ":language_md",
        "//:empty_md",
    ],
)
