load("@bazel_ebook//build:rules.bzl", "ebook_pdf", "markdown_lib")

package(default_visibility = ["//visibility:public"])

markdown_lib(
    name = "draft_spec_md",
    srcs = ["draft-spec.md"],
)

ebook_pdf(
    name = "draft-spec-pdf",
    metadata_xml = "empty.xml",
    title_yaml = "empty.yaml",
    tags = ["pdf"],
    deps = [":draft_spec_md"],
)

markdown_lib(
    name = "spec_md",
    srcs = ["spec.md"],
)

ebook_pdf(
    name = "spec-pdf",
    metadata_xml = "empty.xml",
    title_yaml = "empty.yaml",
    tags = ["pdf"],
    deps = [":spec_md"],
)

markdown_lib(
    name = "lhdl_proposal_md",
    srcs = ["lhdl-proposal.md"],
)

ebook_pdf(
    name = "lhdl-proposal-pdf",
    metadata_xml = "empty.xml",
    title_yaml = "empty.yaml",
    tags = ["pdf"],
    deps = [":lhdl_proposal_md"],
)

markdown_lib(
    name = "readme_md",
    srcs = ["README.md"],
)

ebook_pdf(
    name = "readme-pdf",
    metadata_xml = "empty.xml",
    title_yaml = "empty.yaml",
    tags = ["pdf"],
    deps = [":readme_md"],
)
