# SPDX-License-Identifier: Apache-2.0
# A workspace with one dependency: TxHDL, from its GitHub mirror, at
# a named commit. Rust and the C toolchain it links with come with
# TxHDL's build; the machine needs Bazelisk and Git, and nothing else.
module(
    name = "blinky",
    version = "0.0.0",
)

bazel_dep(name = "rules_rust", version = "0.74.0")
bazel_dep(name = "txhdl", version = "0.0.0")
git_override(
    module_name = "txhdl",
    commit = "eed5b7fdb0e44480019554a9be06fe06fc6c5b08",
    remote = "https://github.com/filmil/hdl-txhdl.git",
)
